locals {
  name_prefix = var.deployment_name
  common_tags = merge({
    deployment = var.deployment_name
    managed-by = "terraform"
    component  = "telnyx-contact-center"
  }, var.tags)
}

# Password is generated by Terraform but NEVER surfaced as a plain output —
# same rationale as the AWS/GCP roots' random_password.db: it only ever
# lands in the shared Key Vault secret below. The wizard reads it back at
# runtime via `az keyvault secret show`, not via `terraform output`.
resource "random_password" "db" {
  length  = 28
  special = true
  # Characters Postgres/the Azure connection-string parser rejects or
  # mishandles: / @ " and space — same restricted set the AWS/GCP roots use
  # (both are Postgres under the hood).
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

# ===========================================================================
# Azure Database for PostgreSQL — Flexible Server, VNet-integrated (private
# access, no public endpoint) — the Azure equivalent of RDS in a private
# subnet / Cloud SQL's private IP. Requires the delegated subnet +
# private DNS zone link created by cc-network-azure (see that module's
# header) to already exist; Terraform sees this dependency automatically
# via the subnet_id/private_dns_zone_id resource references below, unlike
# GCP's cc-database-gcp (which needs an explicit module-level depends_on
# because its equivalent link is only passed as a plain string).
# ===========================================================================

resource "azurerm_postgresql_flexible_server" "main" {
  name                = "${local.name_prefix}-pg"
  resource_group_name = var.resource_group_name
  location            = var.location

  delegated_subnet_id           = var.db_subnet_id
  private_dns_zone_id           = var.private_dns_zone_id
  public_network_access_enabled = false

  sku_name   = var.db_sku_name
  version    = var.db_version
  storage_mb = var.db_storage_mb

  administrator_login    = var.db_username
  administrator_password = random_password.db.result

  backup_retention_days        = var.backup_retention_days
  geo_redundant_backup_enabled = var.geo_redundant_backup

  # ZoneRedundant standby replica for HA/Large sizing — Azure's equivalent
  # of RDS multi_az / Cloud SQL's REGIONAL availability_type. Omitted
  # entirely (not just set to a "none" value) when HA is off, since the
  # high_availability block's mere presence changes Flexible Server's
  # billing tier regardless of mode.
  dynamic "high_availability" {
    for_each = var.db_ha_enabled ? [1] : []
    content {
      mode = "ZoneRedundant"
    }
  }

  lifecycle {
    # storage_mb: mirrors the AWS/GCP roots' escape hatch for
    # operator-driven tier/storage changes made outside Terraform (e.g.
    # Azure Portal autoscale-storage growth) without Terraform fighting to
    # revert them on the next apply.
    #
    # zone: Azure Flexible Server AUTO-ASSIGNS an availability zone at
    # creation time when the operator doesn't pin one (this module never
    # sets `zone` explicitly). Terraform then reads that auto-assigned
    # value back into state, but on every SUBSEQUENT apply the provider
    # tries to reconcile state back toward "unset", which the Flexible
    # Server API rejects outright with "`zone` can only be changed when
    # exchanged with the zone specified in
    # `high_availability.0.standby_availability_zone`" — a real, live-apply
    # failure discovered running a second apply against already-provisioned
    # infra (not caught by `terraform plan`, which only diffs against the
    # last-known state, not a live API round-trip). No AWS/GCP equivalent:
    # RDS Multi-AZ and Cloud SQL's REGIONAL availability_type don't surface
    # a similarly independently-mutable zone attribute.
    ignore_changes  = [storage_mb, zone]
    prevent_destroy = false
  }

  tags = local.common_tags

  # NOTE ON DEPENDENCY ORDERING: this resource requires the delegated
  # subnet + private DNS zone virtual network link (both created by
  # cc-network-azure) to be FULLY provisioned first, or Flexible Server
  # creation fails outright. `delegated_subnet_id`/`private_dns_zone_id`
  # above are plain string variables here (not resource references), so
  # Terraform cannot infer that ordering automatically within this module.
  # The ROOT module MUST add `depends_on = [module.network]` on this
  # module's block (see azure/single-node/main.tf) to force it explicitly —
  # identical requirement and fix to cc-database-gcp's same-named note.
}

resource "azurerm_postgresql_flexible_server_database" "main" {
  name      = var.db_name
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# ===========================================================================
# Extension allow-list — Azure Database for PostgreSQL Flexible Server
# rejects `CREATE EXTENSION` outright ("extension ... is not allow-listed
# for users in Azure Database for PostgreSQL") for ANY extension not first
# added to this server-level `azure.extensions` parameter, even ones
# bundled with stock Postgres like pgcrypto. Neither RDS (AWS) nor Cloud
# SQL (GCP) have an equivalent gate — CREATE EXTENSION just works there,
# which is why this has no AWS/GCP counterpart module.
#
# Discovered as a REAL, live-apply-invisible failure: the app's own schema
# migration (lib/postgres-schema.mjs's ensurePostgresSchema, via
# `CREATE EXTENSION IF NOT EXISTS pgcrypto;`) ran inside a single
# transaction that also creates every application table. pgcrypto's
# rejection triggered a ROLLBACK of the ENTIRE transaction — so the app
# came up "healthy" (the /api/health check only verifies a raw TCP
# connection, not schema readiness) with a completely empty `public`
# schema: no `users` table, seedDefaultOwner() had nothing to write into,
# and the owner login the wizard prints at the end of the deploy silently
# never worked. `terraform plan`/`apply` succeed either way — this is a
# runtime-only failure inside the APPLICATION's own migration step, not
# Terraform's, which is exactly why it needs a Terraform-managed fix here:
# the extension must be allow-listed BEFORE the app's first schema-init
# run, and only Terraform (or the operator) has the server-level
# permission to set this parameter.
#
# Add any other extension the app starts requiring to this
# comma-separated value (e.g. "pgcrypto,uuid-ossp") — search
# lib/postgres-schema.mjs for `CREATE EXTENSION` to find the current set.
#
# depends_on = [azurerm_postgresql_flexible_server_database.main]: both this
# resource and the database above declare their only Terraform-graph
# dependency as the bare azurerm_postgresql_flexible_server.main, so with no
# explicit ordering between the two SIBLING resources Terraform is free to
# submit the database CREATE and this server-level `azure.extensions`
# configuration update concurrently on a fresh apply. Azure Postgres
# Flexible Server commonly rejects overlapping control-plane operations
# against the same server with a transient `ServerBusy` / 409, which would
# make first-time wizard provisioning flaky (and non-deterministic — plan
# always succeeds, only a live concurrent apply can hit it) before the app
# ever gets a chance to start. Forcing this resource to wait for the
# database serializes the two post-server operations without changing
# anything about WHAT gets created, just the order.
resource "azurerm_postgresql_flexible_server_configuration" "extensions" {
  name      = "azure.extensions"
  server_id = azurerm_postgresql_flexible_server.main.id
  value     = "pgcrypto"

  depends_on = [azurerm_postgresql_flexible_server_database.main]
}

# Key Vault secret — full connection string + individual fields, written
# into the SHARED per-deployment vault (see cc-secrets-azure's header for
# why one vault, not one per module). Terraform-owned end to end (password
# generated here, value written here), unlike the app/env secret
# (cc-secrets-azure module), which Terraform creates as an empty
# placeholder the wizard populates after Telnyx bootstrap.
resource "azurerm_key_vault_secret" "db" {
  name         = "${local.name_prefix}-db-credentials"
  key_vault_id = var.key_vault_id
  value = jsonencode({
    username = "${var.db_username}"
    password = random_password.db.result
    engine   = "postgres"
    host     = azurerm_postgresql_flexible_server.main.fqdn
    port     = 5432
    dbname   = var.db_name
  })

  tags = local.common_tags
}
