// Browser-safe catalogue. These original tones are generated by
// scripts/generate-notification-sounds.mjs and served locally.
export const NOTIFICATION_SOUNDS = Object.freeze([
  { id: 'glass', name: 'Glass chime', duration: 3.2 },
  { id: 'marimba', name: 'Marimba', duration: 3.4 },
  { id: 'aurora', name: 'Aurora', duration: 4 },
  { id: 'pulse', name: 'Soft pulse', duration: 3.2 },
  { id: 'doorbell', name: 'Doorbell', duration: 3.6 },
  { id: 'orbit', name: 'Orbit', duration: 3.6 },
  { id: 'cascade', name: 'Cascade', duration: 3.8 },
  { id: 'beacon', name: 'Beacon', duration: 3.2 },
  { id: 'bloom', name: 'Bloom', duration: 4 },
  { id: 'digital', name: 'Digital bell', duration: 3.4 },
].map(sound => Object.freeze({ ...sound, src: `/audio/notifications/${sound.id}.wav` })));
// Channels whose offers ring in the portal header (and play a sound) while
// the agent is away from the desktop: the native-lifecycle channels. Voice
// rings through the softphone instead.
export const NOTIFICATION_CHANNELS = Object.freeze(['email', 'chat', 'whatsapp', 'sms', 'video']);
export const NOTIFICATION_LOOP_GAP_MS = 1000;
const CHANNEL_DEFAULTS = Object.freeze({
  email: { enabled: true, sound: 'glass' }, chat: { enabled: true, sound: 'marimba' },
  whatsapp: { enabled: false, sound: 'aurora' }, sms: { enabled: false, sound: 'pulse' },
  video: { enabled: true, sound: 'doorbell' },
});
export const DEFAULT_NOTIFICATION_SOUNDS = Object.freeze({
  volume: 75,
  channels: Object.freeze(Object.fromEntries(NOTIFICATION_CHANNELS.map((channel) => [channel,
    Object.freeze({ ...CHANNEL_DEFAULTS[channel], loop: true }),
  ]))),
});

const object = value => value && typeof value === 'object' && !Array.isArray(value);
const knownSound = id => NOTIFICATION_SOUNDS.some(sound => sound.id === id);
export function notificationSoundsFromAppSettings(settings) {
  const raw = settings?.notification_sounds;
  return {
    volume: Number.isInteger(raw?.volume) && raw.volume >= 0 && raw.volume <= 100 ? raw.volume : DEFAULT_NOTIFICATION_SOUNDS.volume,
    channels: Object.fromEntries(NOTIFICATION_CHANNELS.map(channel => {
      const fallback = DEFAULT_NOTIFICATION_SOUNDS.channels[channel], value = raw?.channels?.[channel];
      return [channel, {
        enabled: typeof value?.enabled === 'boolean' ? value.enabled : fallback.enabled,
        sound: knownSound(value?.sound) ? value.sound : fallback.sound,
        loop: typeof value?.loop === 'boolean' ? value.loop : fallback.loop,
      }];
    })),
  };
}

export function parseNotificationSounds(raw) {
  if (!object(raw) || !Number.isInteger(raw.volume) || raw.volume < 0 || raw.volume > 100 || !object(raw.channels)) {
    throw new Error('Notification volume must be a whole number from 0 to 100 and channel settings are required.');
  }
  // A channel added after a settings page was opened (video, in 2026-09) is
  // simply absent from that page's save: it keeps its default. Channels that
  // are present must be complete and valid.
  for (const channel of NOTIFICATION_CHANNELS) {
    const value = raw.channels[channel];
    if (value === undefined) continue;
    if (!object(value) || typeof value.enabled !== 'boolean' || typeof value.loop !== 'boolean' || !knownSound(value.sound)) {
      throw new Error(`Choose a valid notification sound, enabled state and loop setting for ${channel}.`);
    }
  }
  return notificationSoundsFromAppSettings({ notification_sounds: raw });
}

export async function loadNotificationSounds(db) {
  const result = await db.query("SELECT cc_settings FROM app_settings WHERE id='default' LIMIT 1");
  return notificationSoundsFromAppSettings(result.rows[0]?.cc_settings);
}

// ------------------------------------------------------------ per-user overrides
//
// Agents may reassign sounds in their profile. Only the fields they changed
// are stored, so anything they left alone keeps following the admin's
// system settings. `null` means "use the system settings".
export function parseNotificationSoundOverrides(raw) {
  if (raw === null || raw === undefined) return null;
  if (!object(raw)) throw new Error('Notification sound overrides must be an object or null.');
  const overrides = {};
  if (raw.volume !== undefined) {
    if (!Number.isInteger(raw.volume) || raw.volume < 0 || raw.volume > 100) throw new Error('Notification volume must be a whole number from 0 to 100.');
    overrides.volume = raw.volume;
  }
  if (raw.channels !== undefined) {
    if (!object(raw.channels)) throw new Error('Channel overrides must be an object.');
    const channels = {};
    for (const channel of NOTIFICATION_CHANNELS) {
      const value = raw.channels[channel];
      if (value === undefined) continue;
      if (!object(value)) throw new Error(`Invalid notification override for ${channel}.`);
      const patch = {};
      if (value.enabled !== undefined) { if (typeof value.enabled !== 'boolean') throw new Error(`Invalid enabled flag for ${channel}.`); patch.enabled = value.enabled; }
      if (value.loop !== undefined) { if (typeof value.loop !== 'boolean') throw new Error(`Invalid loop flag for ${channel}.`); patch.loop = value.loop; }
      if (value.sound !== undefined) { if (!knownSound(value.sound)) throw new Error(`Unknown notification sound for ${channel}.`); patch.sound = value.sound; }
      if (Object.keys(patch).length) channels[channel] = patch;
    }
    if (Object.keys(channels).length) overrides.channels = channels;
  }
  return Object.keys(overrides).length ? overrides : null;
}

export function mergeNotificationSounds(system, overrides) {
  const base = notificationSoundsFromAppSettings({ notification_sounds: system });
  if (!overrides) return base;
  return {
    volume: overrides.volume ?? base.volume,
    channels: Object.fromEntries(NOTIFICATION_CHANNELS.map(channel => [channel, { ...base.channels[channel], ...(overrides.channels?.[channel] || {}) }])),
  };
}

// The subset of `effective` that differs from `system`, ready to store.
export function notificationSoundOverridesFrom(system, effective) {
  const base = notificationSoundsFromAppSettings({ notification_sounds: system });
  const overrides = {};
  if (effective.volume !== base.volume) overrides.volume = effective.volume;
  const channels = {};
  for (const channel of NOTIFICATION_CHANNELS) {
    const patch = {};
    for (const key of ['enabled', 'sound', 'loop']) if (effective.channels?.[channel]?.[key] !== undefined && effective.channels[channel][key] !== base.channels[channel][key]) patch[key] = effective.channels[channel][key];
    if (Object.keys(patch).length) channels[channel] = patch;
  }
  if (Object.keys(channels).length) overrides.channels = channels;
  return Object.keys(overrides).length ? overrides : null;
}

export async function loadNotificationSoundsForUser(db, userId) {
  const [system, user] = await Promise.all([
    loadNotificationSounds(db),
    db.query('SELECT notification_sounds FROM users WHERE id=$1', [String(userId)]),
  ]);
  let overrides = null;
  try { overrides = parseNotificationSoundOverrides(user.rows[0]?.notification_sounds ?? null); } catch { overrides = null; }
  return { system, overrides, effective: mergeNotificationSounds(system, overrides) };
}

export async function saveNotificationSoundOverrides(db, userId, raw) {
  const overrides = parseNotificationSoundOverrides(raw);
  await db.query('UPDATE users SET notification_sounds=$2::jsonb WHERE id=$1', [String(userId), overrides ? JSON.stringify(overrides) : null]);
  return loadNotificationSoundsForUser(db, userId);
}
