const EN = {
  loading: "Loading document preview…", retry: "Try again", empty: "This document is empty.",
  sheet: "Sheet", previous: "Previous rows", next: "Next rows", rows: "Rows", of: "of",
  limited: "This is a limited preview. Download the original to see the complete file.",
  invalid_document: "This document could not be opened. It may be damaged or password protected.",
  preview_too_large: "This file is too large to preview (maximum 20 MB input). Download the original to open it.",
  preview_timeout: "The preview took too long to prepare. Try again or download the original.",
  preview_busy: "Other previews are being prepared. Please try again shortly.",
  preview_too_complex: "This document is too complex to preview. Download the original to open it.",
  word_simplified: "Formatting is simplified. Download the original for the full layout.",
  word_omitted: "Some document content could not be shown. Download the original for the complete document.",
  word_text: "Text-only Word preview. Download the original for formatting and images.",
  conversion_failed: "The preview could not be prepared. Try again or download the original.",
  unsupported_document: "A preview is not available for this file type.",
  access_denied: "Access to this file has expired or is no longer available. Reopen it from the conversation.",
};
const PL = {
  loading: "Ładowanie podglądu dokumentu…", retry: "Spróbuj ponownie", empty: "Ten dokument jest pusty.",
  sheet: "Arkusz", previous: "Poprzednie wiersze", next: "Następne wiersze", rows: "Wiersze", of: "z",
  limited: "To jest ograniczony podgląd. Pobierz oryginał, aby zobaczyć cały plik.",
  invalid_document: "Nie można otworzyć dokumentu. Plik może być uszkodzony lub chroniony hasłem.",
  preview_too_large: "Plik jest za duży do podglądu (maksymalnie 20 MB). Pobierz oryginał, aby go otworzyć.",
  preview_timeout: "Przygotowanie podglądu trwało zbyt długo. Spróbuj ponownie lub pobierz oryginał.",
  preview_busy: "Trwa przygotowywanie innych podglądów. Spróbuj ponownie za chwilę.",
  preview_too_complex: "Dokument jest zbyt złożony do podglądu. Pobierz oryginał, aby go otworzyć.",
  word_simplified: "Formatowanie jest uproszczone. Pobierz oryginał, aby zobaczyć pełny układ.",
  word_omitted: "Nie udało się wyświetlić części dokumentu. Pobierz oryginał, aby zobaczyć całą treść.",
  word_text: "Tekstowy podgląd Worda. Pobierz oryginał, aby zobaczyć formatowanie i obrazy.",
  conversion_failed: "Nie udało się przygotować podglądu. Spróbuj ponownie lub pobierz oryginał.",
  unsupported_document: "Podgląd tego typu pliku nie jest dostępny.",
  access_denied: "Dostęp do pliku wygasł lub jest niedostępny. Otwórz plik ponownie z rozmowy.",
};

const TRANSLATIONS = {
  pl: PL,
  de: {
    loading: "Dokumentvorschau wird geladen…", retry: "Erneut versuchen", empty: "Dieses Dokument ist leer.",
    sheet: "Tabellenblatt", previous: "Vorherige Zeilen", next: "Nächste Zeilen", rows: "Zeilen", of: "von",
    limited: "Dies ist eine begrenzte Vorschau. Laden Sie das Original herunter, um die gesamte Datei zu sehen.",
    invalid_document: "Das Dokument konnte nicht geöffnet werden. Es ist möglicherweise beschädigt oder passwortgeschützt.",
    preview_too_large: "Die Datei ist für die Vorschau zu groß (maximal 20 MB). Laden Sie das Original herunter.",
    preview_timeout: "Die Vorschau hat zu lange gedauert. Versuchen Sie es erneut oder laden Sie das Original herunter.",
    preview_busy: "Andere Vorschauen werden vorbereitet. Bitte versuchen Sie es gleich erneut.",
    preview_too_complex: "Das Dokument ist für die Vorschau zu komplex. Laden Sie das Original herunter.",
    word_simplified: "Die Formatierung ist vereinfacht. Laden Sie das Original für das vollständige Layout herunter.",
    word_omitted: "Einige Inhalte konnten nicht angezeigt werden. Laden Sie das vollständige Original herunter.",
    word_text: "Word-Vorschau als Text. Laden Sie das Original für Formatierung und Bilder herunter.",
    conversion_failed: "Die Vorschau konnte nicht erstellt werden. Versuchen Sie es erneut oder laden Sie das Original herunter.",
    unsupported_document: "Für diesen Dateityp ist keine Vorschau verfügbar.",
    access_denied: "Der Dateizugriff ist abgelaufen oder nicht mehr verfügbar. Öffnen Sie die Datei erneut aus dem Gespräch.",
  },
  fr: {
    loading: "Chargement de l’aperçu…", retry: "Réessayer", empty: "Ce document est vide.",
    sheet: "Feuille", previous: "Lignes précédentes", next: "Lignes suivantes", rows: "Lignes", of: "sur",
    limited: "Cet aperçu est limité. Téléchargez l’original pour consulter le fichier complet.",
    invalid_document: "Impossible d’ouvrir ce document. Il est peut-être endommagé ou protégé par un mot de passe.",
    preview_too_large: "Ce fichier est trop volumineux pour l’aperçu (20 Mo maximum). Téléchargez l’original.",
    preview_timeout: "La préparation de l’aperçu a pris trop de temps. Réessayez ou téléchargez l’original.",
    preview_busy: "D’autres aperçus sont en cours de préparation. Réessayez dans un instant.",
    preview_too_complex: "Ce document est trop complexe pour l’aperçu. Téléchargez l’original.",
    word_simplified: "La mise en forme est simplifiée. Téléchargez l’original pour la mise en page complète.",
    word_omitted: "Certains éléments ne peuvent pas être affichés. Téléchargez le document original complet.",
    word_text: "Aperçu Word en texte seul. Téléchargez l’original pour la mise en forme et les images.",
    conversion_failed: "Impossible de préparer l’aperçu. Réessayez ou téléchargez l’original.",
    unsupported_document: "Aucun aperçu n’est disponible pour ce type de fichier.",
    access_denied: "L’accès au fichier a expiré ou n’est plus disponible. Ouvrez-le à nouveau depuis la conversation.",
  },
  es: {
    loading: "Cargando vista previa…", retry: "Reintentar", empty: "Este documento está vacío.",
    sheet: "Hoja", previous: "Filas anteriores", next: "Filas siguientes", rows: "Filas", of: "de",
    limited: "Esta vista previa es limitada. Descarga el original para ver el archivo completo.",
    invalid_document: "No se pudo abrir el documento. Puede estar dañado o protegido con contraseña.",
    preview_too_large: "El archivo es demasiado grande para la vista previa (máximo 20 MB). Descarga el original.",
    preview_timeout: "La vista previa tardó demasiado. Reintenta o descarga el original.",
    preview_busy: "Se están preparando otras vistas previas. Reintenta en un momento.",
    preview_too_complex: "El documento es demasiado complejo para la vista previa. Descarga el original.",
    word_simplified: "El formato está simplificado. Descarga el original para ver el diseño completo.",
    word_omitted: "No se pudo mostrar parte del contenido. Descarga el documento original completo.",
    word_text: "Vista previa de Word solo como texto. Descarga el original para ver el formato y las imágenes.",
    conversion_failed: "No se pudo preparar la vista previa. Reintenta o descarga el original.",
    unsupported_document: "No hay vista previa para este tipo de archivo.",
    access_denied: "El acceso al archivo caducó o ya no está disponible. Vuelve a abrirlo desde la conversación.",
  },
  ar: {
    loading: "جارٍ تحميل معاينة المستند…", retry: "إعادة المحاولة", empty: "هذا المستند فارغ.",
    sheet: "ورقة", previous: "الصفوف السابقة", next: "الصفوف التالية", rows: "الصفوف", of: "من",
    limited: "هذه معاينة محدودة. نزّل الملف الأصلي لعرضه بالكامل.",
    invalid_document: "تعذّر فتح المستند. قد يكون تالفًا أو محميًا بكلمة مرور.",
    preview_too_large: "الملف كبير جدًا للمعاينة (الحد الأقصى 20 ميغابايت). نزّل الملف الأصلي.",
    preview_timeout: "استغرق إعداد المعاينة وقتًا طويلًا. أعد المحاولة أو نزّل الملف الأصلي.",
    preview_busy: "يجري إعداد معاينات أخرى. حاول مجددًا بعد قليل.",
    preview_too_complex: "المستند معقد جدًا للمعاينة. نزّل الملف الأصلي لفتحه.",
    word_simplified: "التنسيق مبسّط. نزّل الملف الأصلي لعرض التخطيط الكامل.",
    word_omitted: "تعذّر عرض بعض محتويات المستند. نزّل الملف الأصلي لعرضه بالكامل.",
    word_text: "معاينة Word نصية فقط. نزّل الملف الأصلي لعرض التنسيق والصور.",
    conversion_failed: "تعذّر إعداد المعاينة. أعد المحاولة أو نزّل الملف الأصلي.",
    unsupported_document: "لا تتوفر معاينة لهذا النوع من الملفات.",
    access_denied: "انتهت صلاحية الوصول إلى الملف أو لم يعد متاحًا. افتحه مجددًا من المحادثة.",
  },
  he: {
    loading: "טוען תצוגה מקדימה…", retry: "נסה שוב", empty: "המסמך הזה ריק.",
    sheet: "גיליון", previous: "שורות קודמות", next: "שורות הבאות", rows: "שורות", of: "מתוך",
    limited: "זו תצוגה מקדימה מוגבלת. הורד את המקור כדי לראות את הקובץ המלא.",
    invalid_document: "לא ניתן לפתוח את המסמך. ייתכן שהוא פגום או מוגן בסיסמה.",
    preview_too_large: "הקובץ גדול מדי לתצוגה מקדימה (עד 20 MB). הורד את המקור.",
    preview_timeout: "הכנת התצוגה המקדימה ארכה זמן רב מדי. נסה שוב או הורד את המקור.",
    preview_busy: "תצוגות מקדימות אחרות נמצאות בהכנה. נסה שוב בעוד רגע.",
    preview_too_complex: "המסמך מורכב מדי לתצוגה מקדימה. הורד את המקור כדי לפתוח אותו.",
    word_simplified: "העיצוב מוצג באופן פשוט. הורד את המקור לצפייה בפריסה המלאה.",
    word_omitted: "לא ניתן להציג חלק מתוכן המסמך. הורד את המסמך המקורי המלא.",
    word_text: "תצוגת Word כטקסט בלבד. הורד את המקור לצפייה בעיצוב ובתמונות.",
    conversion_failed: "לא ניתן להכין תצוגה מקדימה. נסה שוב או הורד את המקור.",
    unsupported_document: "אין תצוגה מקדימה לסוג הקובץ הזה.",
    access_denied: "הגישה לקובץ פגה או אינה זמינה עוד. פתח אותו מחדש מתוך השיחה.",
  },
};

export function documentPreviewCopy(locale) {
  return TRANSLATIONS[String(locale).toLowerCase().split("-")[0]] || EN;
}
