locals {
  name_prefix = var.deployment_name
  common_labels = merge({
    deployment = var.deployment_name
    managed-by = "terraform"
    component  = "telnyx-contact-center"
  }, var.labels)
}

# Password is generated by Terraform but NEVER surfaced as a plain output —
# same rationale as the AWS root's random_password.db: it only ever lands in
# the Secret Manager secret below. The wizard reads it back at runtime via
# `gcloud secrets versions access`, not via `terraform output`.
resource "random_password" "db" {
  length  = 28
  special = true
  # Characters Cloud SQL Postgres rejects/mishandles in passwords passed
  # through the gcloud CLI and connection strings: / @ " and space (same
  # restricted set as the AWS root, kept identical rather than special-cased
  # per-provider since both are Postgres under the hood).
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

# NOTE ON DEPENDENCY ORDERING: this module's google_sql_database_instance
# requires the private-services-access VPC peering (cc-network-gcp's
# google_service_networking_connection) to already exist, or instance
# creation fails outright with a peering-not-found error. Terraform can't see
# that dependency automatically since it only touches this module through
# `vpc_id` (a plain string, not a resource reference) — the ROOT module
# MUST add `depends_on = [module.network]` on this module's block (see
# gcp/single-node/main.tf) to force the ordering explicitly.

resource "google_sql_database_instance" "main" {
  name                = "${local.name_prefix}-pg"
  project             = var.project_id
  region              = var.region
  database_version    = var.db_version
  deletion_protection = var.deletion_protection

  settings {
    tier = var.db_tier
    # Cloud SQL now has two Editions: ENTERPRISE (traditional, supports
    # custom machine tiers like db-custom-N-M) and ENTERPRISE_PLUS (newer,
    # only accepts predefined db-perf-optimized-N-* tiers). Newly-enrolled
    # GCP projects/regions can silently default to ENTERPRISE_PLUS when this
    # field is left unset, which then rejects var.db_tier's db-custom-*
    # value outright — confirmed via a real E2E run (2026-07-09, cc-gcp1):
    #   "Invalid Tier (db-custom-1-3840) for (ENTERPRISE_PLUS) Edition."
    # Pinning ENTERPRISE explicitly keeps db_tier's custom-machine-type
    # contract working regardless of the project's default.
    edition           = "ENTERPRISE"
    availability_type = var.db_availability_type
    disk_size         = var.db_disk_size_gb
    disk_type         = "PD_SSD"
    disk_autoresize   = true

    ip_configuration {
      ipv4_enabled    = false
      private_network = var.vpc_id
    }

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      transaction_log_retention_days = var.backup_retention_days
    }

    database_flags {
      # STATIC parameter equivalent of the AWS root's max_connections=300
      # pending-reboot bump — set here as an instance-level flag instead
      # (Cloud SQL applies flag changes with a restart when required, same
      # net effect as RDS's apply_method=pending-reboot).
      name  = "max_connections"
      value = "300"
    }

    user_labels = merge(local.common_labels, { name = "${local.name_prefix}-pg" })
  }

  lifecycle {
    # Same escape hatch as the AWS root: allow an operator-driven tier/disk
    # change without Terraform fighting Cloud SQL's own autoresize (disk
    # size grows automatically via disk_autoresize, which would otherwise
    # show a perpetual diff against the value recorded here at create time).
    ignore_changes = [settings[0].disk_size]
  }
}

resource "google_sql_database" "main" {
  name     = var.db_name
  project  = var.project_id
  instance = google_sql_database_instance.main.name

  # On `terraform destroy`, the provider's default behavior is to call
  # Cloud SQL's DELETE-database API explicitly, BEFORE the instance itself
  # is torn down — even though the whole instance is about to be destroyed
  # in the same operation anyway. Postgres (unlike MySQL) refuses that
  # explicit delete outright if there's any live connection to the
  # database ("database ... is being accessed by other users"), which is
  # essentially guaranteed here since the app node holds an open
  # connection pool to it. Confirmed via a real `cc destroy` E2E run
  # against a live GCP project:
  #   "failed to delete database contact_center. Detail: pq: database
  #   \"contact_center\" is being accessed by other users."
  # deletion_policy = "ABANDON" tells the provider to drop this resource
  # from Terraform state WITHOUT calling the delete API on destroy — safe
  # here specifically because google_sql_database_instance.main's own
  # destroy (which happens right after, and which this deploy already
  # backs up via null_resource.final_backup) deletes the whole instance,
  # database included, regardless. AWS's RDS equivalent (cc-database
  # module) never hits this class of bug because aws_db_instance has no
  # separate database/user sub-resources to explicitly delete in the first
  # place — the whole DB just goes with the instance.
  deletion_policy = "ABANDON"
}

resource "google_sql_user" "app" {
  name     = var.db_username
  project  = var.project_id
  instance = google_sql_database_instance.main.name
  password = random_password.db.result

  # Same rationale as google_sql_database.main's deletion_policy above:
  # Postgres refuses to DROP ROLE for a role that still owns objects
  # (confirmed in the same E2E run — "role \"contact_center\" cannot be
  # dropped because some objects depend on it Details: 120 objects in
  # database contact_center", since this user owns every table/sequence/
  # index the app created). ABANDON skips the explicit DROP USER call and
  # lets the instance-level destroy remove it along with everything else.
  deletion_policy = "ABANDON"
}

# ===========================================================================
# Final backup on destroy — Cloud SQL has no built-in "keep a snapshot when
# the instance is deleted" flag the way RDS does (final_snapshot_identifier).
# The closest equivalent is triggering an on-demand backup right before
# deletion via a destroy-time local-exec provisioner calling `gcloud sql
# backups create`. Gated on skip_final_backup exactly like the AWS root's
# skip_final_snapshot, same default (false = safe/keep a backup).
# ===========================================================================

resource "null_resource" "final_backup" {
  count = var.skip_final_backup ? 0 : 1

  triggers = {
    instance_name = google_sql_database_instance.main.name
    project_id    = var.project_id
  }

  provisioner "local-exec" {
    when    = destroy
    command = "gcloud sql backups create --instance=${self.triggers.instance_name} --project=${self.triggers.project_id} --description='cc destroy final backup' || echo 'WARNING: final Cloud SQL backup failed — instance is about to be destroyed anyway, continuing.'"
  }

  # depends_on covers BOTH ordering requirements for the final backup:
  #   1. google_sql_database_instance.main — the instance itself must exist
  #      before the backup is created (backups are scoped to an instance).
  #   2. google_sql_database.main / google_sql_user.app — these are SIBLING
  #      dependents of the instance (not descendants of each other), so on
  #      `terraform destroy` Terraform is otherwise free to destroy them in
  #      parallel with this null_resource. Without an explicit dependency
  #      here, the destroy-time `gcloud sql backups create` provisioner can
  #      run AFTER the app database/user have already been dropped, producing
  #      a "final backup" that no longer contains the application's own data
  #      — silently defeating the entire point of this resource. Depending
  #      on them directly forces Terraform's reverse-destroy-order guarantee
  #      to run the backup first, while the database/user (and only after
  #      that the instance) are torn down.
  depends_on = [
    google_sql_database_instance.main,
    google_sql_database.main,
    google_sql_user.app,
  ]
}

# Secret Manager: full connection string + individual fields — mirrors the
# AWS root's aws_secretsmanager_secret "db". Terraform-owned end to end
# (password generated here, value written here), unlike the app/env secret
# (cc-secrets-gcp module), which Terraform creates as an empty container the
# wizard populates after Telnyx bootstrap.
resource "google_secret_manager_secret" "db" {
  secret_id = "${local.name_prefix}-db-credentials"
  project   = var.project_id

  replication {
    auto {}
  }

  labels = local.common_labels
}

resource "google_secret_manager_secret_version" "db" {
  secret = google_secret_manager_secret.db.id
  secret_data = jsonencode({
    username = var.db_username
    password = random_password.db.result
    engine   = "postgres"
    host     = google_sql_database_instance.main.private_ip_address
    port     = 5432
    dbname   = var.db_name
  })
}
