import assert from "node:assert/strict";
import test from "node:test";

import { getValueByPath } from "../lib/variable-utils.js";

test("getValueByPath resolves webhook array item paths generated by schema picker", () => {
  const payload = {
    custom_headers: [
      { name: "X-Test", value: "ok" },
      { name: "X-Other", value: "ignored" },
    ],
    tags: ["first", "second"],
  };

  assert.equal(
    getValueByPath({ payload }, "payload.custom_headers[].name"),
    "X-Test",
  );
  assert.deepEqual(getValueByPath({ payload }, "payload.tags[]"), [
    "first",
    "second",
  ]);
});
