import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { getPostgresPool } from "@/lib/postgres.mjs";
import { PgDb } from "@/lib/pgdb";
import { isAdmin } from "@/lib/role-utils";
import { normalizeFormDefinition, validateFormDefinition } from "@/lib/forms/form-schema";
import { adminRuntimeLogger, contactCenterRuntimeLogger, platformApiLogger, platformDbLogger, runtimePayload, voiceRuntimeLogger } from "@/lib/runtime-logging.mjs";
async function requireAdmin() { const s = await getServerSession(authOptions); const id = s?.user?.id || null; const email = s?.user?.email || null; if (!id && !email) return null; let u = id ? await PgDb.findUserById(id) : null; if (!u && email) u = await PgDb.findUserByUsername(email); return u && isAdmin(u) ? u : null; }
function mapRow(row) { return row ? { ...row, queue_ids: row.queue_ids || [], queue_names: row.queue_names || [] } : null; }
export async function GET(request, context) { const user = await requireAdmin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { id } = await context.params; const pool = getPostgresPool(); if (!pool) return NextResponse.json({ error: "Server not ready" }, { status: 500 }); const { rows } = await pool.query(`SELECT * FROM form_definitions WHERE id = $1`, [id]); if (!rows[0]) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json({ ok: true, form: mapRow(rows[0]) }); }
export async function PUT(request, context) { const user = await requireAdmin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { id } = await context.params; const pool = getPostgresPool(); if (!pool) return NextResponse.json({ error: "Server not ready" }, { status: 500 }); try { const body = await request.json(); const form = normalizeFormDefinition(body); const validation = validateFormDefinition(form); if (!validation.ok) return NextResponse.json({ error: "Invalid form", details: validation.errors }, { status: 400 }); const username = user.username || user.email || "system"; const { rows } = await pool.query(`UPDATE form_definitions SET name=$1, slug=$2, description=$3, category=$4, status=$5, schema=$6, layout=$7, theme=$8, bindings=$9, actions=$10, queue_ids=$11, queue_names=$12, auto_open=$13, updated_by=$14, updated_at=NOW(), published_at=CASE WHEN $5='published' AND published_at IS NULL THEN NOW() ELSE published_at END WHERE id=$15 RETURNING *`, [form.name, form.slug, form.description, form.category, form.status, JSON.stringify(form.schema), JSON.stringify(form.layout), JSON.stringify(form.theme), JSON.stringify(form.bindings), JSON.stringify(form.actions), form.queue_ids, form.queue_names, form.auto_open, username, id]); if (!rows[0]) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json({ ok: true, form: mapRow(rows[0]) }); } catch (err) { adminRuntimeLogger.error("runtime_error", { ...runtimePayload({ error: typeof error !== "undefined" ? error : typeof err !== "undefined" ? err : undefined, status: typeof status !== "undefined" ? status : undefined }) }); return NextResponse.json({ error: err.code === "23505" ? "A form with this slug already exists" : "Failed to update form" }, { status: 400 }); } }
export async function DELETE(request, context) { const user = await requireAdmin(); if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { id } = await context.params; const pool = getPostgresPool(); if (!pool) return NextResponse.json({ error: "Server not ready" }, { status: 500 }); const username = user.username || user.email || "system"; const { rows } = await pool.query(`UPDATE form_definitions SET status='archived', updated_by=$1, updated_at=NOW() WHERE id=$2 RETURNING *`, [username, id]); if (!rows[0]) return NextResponse.json({ error: "Not found" }, { status: 404 }); return NextResponse.json({ ok: true, form: mapRow(rows[0]) }); }
