import {
  IconCheck,
  IconClock,
  IconX,
  IconCircleOff,
  IconPhone,
  IconAlertCircle,
  IconUser,
  IconBolt,
  IconCoffee,
  IconBell,
  IconBellOff,
  IconBriefcase,
  IconCalendar,
  IconChevronRight,
  IconChevronLeft,
  IconChevronUp,
  IconChevronDown,
  IconHeadset,
  IconMessageCircle,
  IconMail,
  IconPhoneCall,
  IconPhoneOff,
  IconShieldCheck,
  IconShieldLock,
  IconStar,
  IconSun,
  IconMoon,
  IconTool,
  IconUserCheck,
  IconUserX,
  IconWifi,
  IconWorld,
  IconInfoCircle,
  IconHelpCircle,
  IconUserCircle,
  IconUserMinus,
  IconUserPlus,
  IconClockPause,
  IconClockPlay,
  IconCalendarTime,
  IconMapPin,
  IconBuilding,
  IconMicrophone,
  IconMicrophoneOff,
  IconVolume,
  IconVolumeOff,
  IconSparkles,
  IconSettings,
  IconPower,
  IconWalk,
  IconRun,
  IconBattery,
  IconBatteryCharging,
  IconPlane,
  IconHeart,
  IconHeartbeat,
  IconSchool,
  IconBook,
  IconCertificate,
} from "@tabler/icons-react";

export const STATUS_ICON_OPTIONS = [
  { value: "check", label: "Check", Icon: IconCheck },
  { value: "clock", label: "Clock", Icon: IconClock },
  { value: "x", label: "X", Icon: IconX },
  { value: "circle-off", label: "Circle Off", Icon: IconCircleOff },
  { value: "phone", label: "Phone", Icon: IconPhone },
  { value: "alert-circle", label: "Alert", Icon: IconAlertCircle },
  { value: "user", label: "User", Icon: IconUser },
  { value: "bolt", label: "Bolt", Icon: IconBolt },
  { value: "coffee", label: "Coffee", Icon: IconCoffee },
  { value: "bell", label: "Bell", Icon: IconBell },
  { value: "bell-off", label: "Bell Off", Icon: IconBellOff },
  { value: "briefcase", label: "Briefcase", Icon: IconBriefcase },
  { value: "calendar", label: "Calendar", Icon: IconCalendar },
  { value: "calendar-time", label: "Calendar Time", Icon: IconCalendarTime },
  { value: "chevron-right", label: "Chevron Right", Icon: IconChevronRight },
  { value: "chevron-left", label: "Chevron Left", Icon: IconChevronLeft },
  { value: "chevron-up", label: "Chevron Up", Icon: IconChevronUp },
  { value: "chevron-down", label: "Chevron Down", Icon: IconChevronDown },
  { value: "headset", label: "Headset", Icon: IconHeadset },
  { value: "message", label: "Message", Icon: IconMessageCircle },
  { value: "mail", label: "Mail", Icon: IconMail },
  { value: "phone-call", label: "Phone Call", Icon: IconPhoneCall },
  { value: "phone-off", label: "Phone Off", Icon: IconPhoneOff },
  { value: "shield-check", label: "Shield Check", Icon: IconShieldCheck },
  { value: "shield-lock", label: "Shield Lock", Icon: IconShieldLock },
  { value: "star", label: "Star", Icon: IconStar },
  { value: "sun", label: "Sun", Icon: IconSun },
  { value: "moon", label: "Moon", Icon: IconMoon },
  { value: "tool", label: "Tool", Icon: IconTool },
  { value: "user-check", label: "User Check", Icon: IconUserCheck },
  { value: "user-x", label: "User X", Icon: IconUserX },
  { value: "user-circle", label: "User Circle", Icon: IconUserCircle },
  { value: "user-minus", label: "User Minus", Icon: IconUserMinus },
  { value: "user-plus", label: "User Plus", Icon: IconUserPlus },
  { value: "wifi", label: "WiFi", Icon: IconWifi },
  { value: "world", label: "World", Icon: IconWorld },
  { value: "info", label: "Info", Icon: IconInfoCircle },
  { value: "help", label: "Help", Icon: IconHelpCircle },
  { value: "clock-pause", label: "Clock Pause", Icon: IconClockPause },
  { value: "clock-play", label: "Clock Play", Icon: IconClockPlay },
  { value: "map-pin", label: "Map Pin", Icon: IconMapPin },
  { value: "building", label: "Building", Icon: IconBuilding },
  { value: "microphone", label: "Microphone", Icon: IconMicrophone },
  { value: "microphone-off", label: "Microphone Off", Icon: IconMicrophoneOff },
  { value: "volume", label: "Volume", Icon: IconVolume },
  { value: "volume-off", label: "Volume Off", Icon: IconVolumeOff },
  { value: "sparkles", label: "Sparkles", Icon: IconSparkles },
  { value: "settings", label: "Settings", Icon: IconSettings },
  { value: "power", label: "Power", Icon: IconPower },
  { value: "walk", label: "Walk", Icon: IconWalk },
  { value: "run", label: "Run", Icon: IconRun },
  { value: "battery", label: "Battery", Icon: IconBattery },
  {
    value: "battery-charging",
    label: "Battery Charging",
    Icon: IconBatteryCharging,
  },
  { value: "plane", label: "Plane", Icon: IconPlane },
  { value: "heart", label: "Heart", Icon: IconHeart },
  { value: "heartbeat", label: "Heartbeat", Icon: IconHeartbeat },
  { value: "school", label: "School", Icon: IconSchool },
  { value: "book", label: "Book", Icon: IconBook },
  { value: "certificate", label: "Certificate", Icon: IconCertificate },
];

export const STATUS_ICON_MAP = STATUS_ICON_OPTIONS.reduce((acc, item) => {
  acc[item.value] = item.Icon;
  return acc;
}, {});

export const STATUS_NAME_ICON_FALLBACK = {
  Available: IconCheck,
  "On Queue": IconClock,
  Busy: IconX,
  Away: IconCircleOff,
  "Off Queue": IconCircleOff,
  Offline: IconCircleOff,
  Break: IconClock,
  Lunch: IconCoffee,
  Vacation: IconPlane,
  Sick: IconHeartbeat,
  Training: IconSchool,
};

export const DEFAULT_STATUS_ICON = "circle-off";
export const DEFAULT_STATUS_COLOR = "#64748b";

export const STATUS_COLOR_OPTIONS = [
  { value: "#16a34a", label: "Green" },
  { value: "#dc2626", label: "Red" },
  { value: "#f97316", label: "Orange" },
  { value: "#eab308", label: "Yellow" },
  { value: "#2563eb", label: "Blue" },
  { value: "#7c3aed", label: "Purple" },
  { value: "#0d9488", label: "Teal" },
  { value: "#64748b", label: "Slate" },
  { value: "#10b981", label: "Emerald" },
  { value: "#22c55e", label: "Lime" },
  { value: "#14b8a6", label: "Cyan" },
  { value: "#0ea5e9", label: "Sky" },
  { value: "#6366f1", label: "Indigo" },
  { value: "#d946ef", label: "Fuchsia" },
  { value: "#ec4899", label: "Pink" },
  { value: "#f43f5e", label: "Rose" },
  { value: "#a16207", label: "Brown" },
  { value: "#111827", label: "Charcoal" },
];
