// Transcription providers with supported languages and models
// Source: Telnyx OpenAPI spec (2026-02-11)

export const TRANSCRIPTION_PROVIDERS = [
  {
    model_name: "deepgram/nova-2",
    label: "Deepgram Nova 2 (Recommended)",
    provider: "deepgram",
    languages: [
      "auto_detect",
      "bg",
      "ca",
      "zh",
      "zh-CN",
      "zh-Hans",
      "zh-TW",
      "zh-Hant",
      "zh-HK",
      "cs",
      "da",
      "da-DK",
      "nl",
      "nl-BE",
      "en",
      "en-US",
      "en-AU",
      "en-GB",
      "en-NZ",
      "en-IN",
      "et",
      "fi",
      "fr",
      "fr-CA",
      "de",
      "de-CH",
      "el",
      "hi",
      "hu",
      "id",
      "it",
      "ja",
      "ko",
      "ko-KR",
      "lv",
      "lt",
      "ms",
      "no",
      "pl",
      "pt",
      "pt-BR",
      "pt-PT",
      "ro",
      "ru",
      "sk",
      "es",
      "es-419",
      "sv",
      "sv-SE",
      "th",
      "th-TH",
      "tr",
      "uk",
      "vi",
    ],
  },
  {
    model_name: "deepgram/nova-3",
    label: "Deepgram Nova 3 (Multi-lingual)",
    provider: "deepgram",
    languages: [
      "auto_detect",
      "en",
      "en-US",
      "en-AU",
      "en-GB",
      "en-IN",
      "en-NZ",
      "de",
      "nl",
      "sv",
      "sv-SE",
      "da",
      "da-DK",
      "es",
      "es-419",
      "fr",
      "fr-CA",
      "pt",
      "pt-BR",
      "pt-PT",
    ],
  },
  {
    model_name: "deepgram/flux",
    label: "Deepgram Flux (Turn-taking, English only)",
    provider: "deepgram",
    languages: ["en"],
  },
  {
    model_name: "azure/fast",
    label: "Azure Fast",
    provider: "azure",
    requiresRegion: true,
    languages: [
      "auto",
      "af",
      "am",
      "ar",
      "bg",
      "bn",
      "bs",
      "ca",
      "cs",
      "cy",
      "da",
      "de",
      "el",
      "en",
      "es",
      "et",
      "eu",
      "fa",
      "fi",
      "fr",
      "ga",
      "gl",
      "gu",
      "he",
      "hi",
      "hr",
      "hu",
      "hy",
      "id",
      "is",
      "it",
      "ja",
      "ka",
      "kk",
      "km",
      "kn",
      "ko",
      "lo",
      "lt",
      "lv",
      "mk",
      "ml",
      "mn",
      "mr",
      "ms",
      "mt",
      "my",
      "nb",
      "ne",
      "nl",
      "pl",
      "ps",
      "pt",
      "ro",
      "ru",
      "si",
      "sk",
      "sl",
      "so",
      "sq",
      "sr",
      "sv",
      "sw",
      "ta",
      "te",
      "th",
      "tr",
      "uk",
      "ur",
      "uz",
      "vi",
      "wuu",
      "yue",
      "zh",
      "zu",
    ],
  },
  {
    model_name: "distil-whisper/distil-large-v2",
    label: "Distil-Whisper Large v2 (Low latency, English)",
    provider: "distil-whisper",
    languages: ["en"],
  },
  {
    model_name: "openai/whisper-large-v3-turbo",
    label: "OpenAI Whisper Large v3 Turbo (Multi-lingual)",
    provider: "telnyx",
    languages: [
      "auto_detect",
      "en",
      "zh",
      "de",
      "es",
      "ru",
      "ko",
      "fr",
      "ja",
      "pt",
      "tr",
      "pl",
      "ca",
      "nl",
      "ar",
      "sv",
      "it",
      "id",
      "hi",
      "fi",
      "vi",
      "he",
      "uk",
      "el",
      "ms",
      "cs",
      "ro",
      "da",
      "hu",
      "ta",
      "no",
      "th",
      "ur",
      "hr",
      "bg",
      "lt",
      "la",
      "mi",
      "ml",
      "cy",
      "sk",
      "te",
      "fa",
      "lv",
      "bn",
      "sr",
      "az",
      "sl",
      "kn",
      "et",
      "mk",
      "br",
      "eu",
      "is",
      "hy",
      "ne",
      "mn",
      "bs",
      "kk",
      "sq",
      "sw",
      "gl",
      "mr",
      "pa",
      "si",
      "km",
      "sn",
      "yo",
      "so",
      "af",
      "oc",
      "ka",
      "be",
      "tg",
      "sd",
      "gu",
      "am",
      "yi",
      "lo",
      "uz",
      "fo",
      "ht",
      "ps",
      "tk",
      "nn",
      "mt",
      "sa",
      "lb",
      "my",
      "bo",
      "tl",
      "mg",
      "as",
      "tt",
      "haw",
      "ln",
      "ha",
      "ba",
      "jw",
      "su",
    ],
  },
];

// Azure regions for STT
export const AZURE_REGIONS = [
  { value: "eastus", label: "East US" },
  { value: "westus2", label: "West US 2" },
  { value: "northcentralus", label: "North Central US" },
  { value: "westeurope", label: "West Europe" },
  { value: "centralindia", label: "Central India" },
  { value: "australiaeast", label: "Australia East" },
];

// Google STT models (for reference)
export const GOOGLE_STT_MODELS = [
  { value: "latest_long", label: "Latest Long" },
  { value: "latest_short", label: "Latest Short" },
  { value: "command_and_search", label: "Command and Search" },
  { value: "phone_call", label: "Phone Call" },
  { value: "video", label: "Video" },
  { value: "default", label: "Default" },
  { value: "medical_conversation", label: "Medical Conversation" },
  { value: "medical_dictation", label: "Medical Dictation" },
];

// Google STT languages (for reference if Google added later)
export const GOOGLE_STT_LANGUAGES = [
  "af", "sq", "am", "ar", "hy", "az", "eu", "bn", "bs", "bg", "my", "ca",
  "yue", "zh", "hr", "cs", "da", "nl", "en", "et", "fil", "fi", "fr", "gl",
  "ka", "de", "el", "gu", "iw", "hi", "hu", "is", "id", "it", "ja", "jv",
  "kn", "kk", "km", "ko", "lo", "lv", "lt", "mk", "ms", "ml", "mr", "mn",
  "ne", "no", "fa", "pl", "pt", "pa", "ro", "ru", "rw", "sr", "si", "sk",
  "sl", "ss", "st", "es", "su", "sw", "sv", "ta", "te", "th", "tn", "tr",
  "ts", "uk", "ur", "uz", "ve", "vi", "xh", "zu",
];
