export const TRANSCRIPTION_PROVIDERS = [
  {
    model_name: "distil-whisper/distil-large-v2",
    voiceApiSupported: false,
    languages: [
      "auto",
      "en","en-US","en-AU","en-GB","en-IN",
      "de","fr","es","pt","it","nl","pl","ru",
      "ar","zh","ja","ko","tr","uk","sv","da",
      "no","fi","cs","ro","hu","bg","hr","sk",
      "sl","lt","lv","et","hi","id","ms","vi","th",
    ],
  },
  {
    model_name: "openai/whisper-large-v3-turbo",
    languages: [
      "en",
      "zh",
      "de",
      "es",
      "ru",
      "ko",
      "fr",
      "ja",
      "pt",
      "tr",
      "pl",
      "ca",
      "nl",
      "ar",
      "sv",
      "it",
      "id",
      "hi",
      "fi",
      "vi",
      "he",
      "uk",
      "el",
      "ms",
      "cs",
      "ro",
      "da",
      "hu",
      "ta",
      "no",
      "th",
      "ur",
      "hr",
      "bg",
      "lt",
      "la",
      "mi",
      "ml",
      "cy",
      "sk",
      "te",
      "fa",
      "lv",
      "bn",
      "sr",
      "az",
      "sl",
      "kn",
      "et",
      "mk",
      "br",
      "eu",
      "is",
      "hy",
      "ne",
      "mn",
      "bs",
      "kk",
      "sq",
      "sw",
      "gl",
      "mr",
      "pa",
      "si",
      "km",
      "sn",
      "yo",
      "so",
      "af",
      "oc",
      "ka",
      "be",
      "tg",
      "sd",
      "gu",
      "am",
      "yi",
      "lo",
      "uz",
      "fo",
      "ht",
      "ps",
      "tk",
      "nn",
      "mt",
      "sa",
      "lb",
      "my",
      "bo",
      "tl",
      "mg",
      "as",
      "tt",
      "haw",
      "ln",
      "ha",
      "ba",
      "jw",
      "su",
      "auto_detect",
    ],
  },
  {
    model_name: "openai/whisper-tiny",
    languages: [
      "en",
      "zh",
      "de",
      "es",
      "ru",
      "ko",
      "fr",
      "ja",
      "pt",
      "tr",
      "pl",
      "ca",
      "nl",
      "ar",
      "sv",
      "it",
      "id",
      "hi",
      "fi",
      "vi",
      "he",
      "uk",
      "el",
      "ms",
      "cs",
      "ro",
      "da",
      "hu",
      "ta",
      "no",
      "th",
      "ur",
      "hr",
      "bg",
      "lt",
      "la",
      "mi",
      "ml",
      "cy",
      "sk",
      "te",
      "fa",
      "lv",
      "bn",
      "sr",
      "az",
      "sl",
      "kn",
      "et",
      "mk",
      "br",
      "eu",
      "is",
      "hy",
      "ne",
      "mn",
      "bs",
      "kk",
      "sq",
      "sw",
      "gl",
      "mr",
      "pa",
      "si",
      "km",
      "sn",
      "yo",
      "so",
      "af",
      "oc",
      "ka",
      "be",
      "tg",
      "sd",
      "gu",
      "am",
      "yi",
      "lo",
      "uz",
      "fo",
      "ht",
      "ps",
      "tk",
      "nn",
      "mt",
      "sa",
      "lb",
      "my",
      "bo",
      "tl",
      "mg",
      "as",
      "tt",
      "haw",
      "ln",
      "ha",
      "ba",
      "jw",
      "su",
      "auto_detect",
    ],
  },
  {
    model_name: "deepgram/nova-2",
    languages: [
      "bg",
      "ca",
      "zh",
      "zh-CN",
      "zh-Hans",
      "zh-TW",
      "zh-Hant",
      "zh-HK",
      "cs",
      "da",
      "da-DK",
      "nl",
      "en",
      "en-US",
      "en-AU",
      "en-GB",
      "en-NZ",
      "en-IN",
      "et",
      "fi",
      "nl-BE",
      "fr",
      "fr-CA",
      "de",
      "de-CH",
      "el",
      "hi",
      "hu",
      "id",
      "it",
      "ja",
      "ko",
      "ko-KR",
      "lv",
      "lt",
      "ms",
      "no",
      "pl",
      "pt",
      "pt-BR",
      "pt-PT",
      "ro",
      "ru",
      "sk",
      "es",
      "es-419",
      "sv",
      "sv-SE",
      "th",
      "th-TH",
      "tr",
      "uk",
      "vi",
      "auto_detect",
    ],
  },
  {
    model_name: "deepgram/nova-3",
    // Voice API TranscriptionStartRequest supports this narrower nova-3 list.
    languages: [
      "en",
      "en-US",
      "en-AU",
      "en-GB",
      "en-IN",
      "en-NZ",
      "de",
      "nl",
      "sv",
      "sv-SE",
      "da",
      "da-DK",
      "es",
      "es-419",
      "fr",
      "fr-CA",
      "pt",
      "pt-BR",
      "pt-PT",
      "auto_detect",
    ],
  },
  {
    model_name: "deepgram/flux",
    // Per Telnyx OpenAPI TranscriptionSettings.language for deepgram/flux:
    // auto = Telnyx language detection controls the language hint
    // multi = no audio hint / multilingual
    voiceApiSupported: false,
    languages: [
      "auto",
      "multi",
      "en",
      "es",
      "fr",
      "de",
      "hi",
      "ru",
      "pt",
      "ja",
      "it",
      "nl",
    ],
  },
  {
    model_name: "speechmatics/standard",
    // Speechmatics realtime supported language codes, per:
    // https://docs.speechmatics.com/speech-to-text/languages
    // Note: Speechmatics `auto` language identification is documented for Batch only,
    // so realtime standalone STT exposes explicit language choices here.
    languages: [
      "en",
      "ba",
      "eu",
      "gl",
      "ga",
      "mt",
      "mn",
      "sw",
      "ug",
      "cy",
      "ar_en",
      "cmn_en",
      "en_ms",
      "en_ta",
      "tl",
      "es-bilingual-en",
      "cmn_en_ms_ta",
    ],
  },
  {
    model_name: "soniox/stt-rt-v4",
    // Soniox STT supports automatic language detection by default and 60+ ISO
    // language codes for hints, per:
    // https://soniox.com/docs/stt/concepts/supported-languages
    // https://soniox.com/docs/stt/concepts/language-hints
    languages: [
      "auto",
      "af",
      "sq",
      "ar",
      "az",
      "eu",
      "be",
      "bn",
      "bs",
      "bg",
      "ca",
      "zh",
      "hr",
      "cs",
      "da",
      "nl",
      "en",
      "et",
      "fi",
      "fr",
      "gl",
      "de",
      "el",
      "gu",
      "he",
      "hi",
      "hu",
      "id",
      "it",
      "ja",
      "kn",
      "kk",
      "ko",
      "lv",
      "lt",
      "mk",
      "ms",
      "ml",
      "mr",
      "no",
      "fa",
      "pl",
      "pt",
      "pa",
      "ro",
      "ru",
      "sr",
      "sk",
      "sl",
      "es",
      "sw",
      "sv",
      "tl",
      "ta",
      "te",
      "th",
      "tr",
      "uk",
      "ur",
      "vi",
      "cy",
    ],
  },
  {
    // AssemblyAI Universal Streaming — only Auto (Multilingual) and English per Telnyx portal
    model_name: "assemblyai/universal-streaming",
    languages: [],
  },
  {
    // xAI Grok STT — exact language list per Telnyx portal
    model_name: "xai/grok-stt",
    languages: [
      "ar",
      "cs",
      "da",
      "de",
      "en",
      "es",
      "fa",
      "fil",
      "fr",
      "hi",
      "id",
      "it",
      "ja",
      "ko",
      "mk",
      "ms",
      "nl",
      "pl",
      "pt",
      "ro",
      "ru",
      "sv",
      "th",
      "tr",
      "vi",
    ],
  },
];


const TRANSCRIPTION_PROVIDER_META = {
  "distil-whisper/distil-large-v2": {
    label: "Distil-Whisper Large v2",
    provider: "distil-whisper",
  },
  "openai/whisper-tiny": {
    label: "OpenAI Whisper Tiny",
    provider: "openai",
  },
  "openai/whisper-large-v3-turbo": {
    label: "OpenAI Whisper Large v3 Turbo",
    provider: "openai",
  },
  "deepgram/nova-2": { label: "Deepgram Nova 2", provider: "deepgram" },
  "deepgram/nova-3": { label: "Deepgram Nova 3", provider: "deepgram" },
  "deepgram/flux": { label: "Deepgram Flux", provider: "deepgram" },
  "speechmatics/standard": {
    label: "Speechmatics Standard",
    provider: "speechmatics",
  },
  "soniox/stt-rt-v4": {
    label: "Soniox STT RT v4",
    provider: "soniox",
  },
  "assemblyai/universal-streaming": {
    label: "AssemblyAI Universal Streaming",
    provider: "assemblyai",
  },
  "xai/grok-stt": { label: "xAI Grok STT", provider: "xai" },
};

for (const provider of TRANSCRIPTION_PROVIDERS) {
  Object.assign(provider, TRANSCRIPTION_PROVIDER_META[provider.model_name] || {});
}

export const NOISE_SUPPRESSION_PROVIDERS = [
  {
    value: "krisp",
    label: "Krisp",
    recommended: false,
  },
  {
    value: "deepfilternet",
    label: "DeepFilterNet",
    configDefaults: { attenuation_limit: 100, mode: "advanced" },
  },
  {
    value: "aicoustics",
    label: "AiCoustics",
    recommended: true,
    configDefaults: { model: "voice_focus_2.0", enhancement_level: 0.8 },
  },
];

export const CALL_FLOW_NOISE_SUPPRESSION_ENGINES = [
  { value: "Denoiser", label: "Denoiser" },
  { value: "DeepFilterNet", label: "DeepFilterNet" },
  { value: "Krisp", label: "Krisp" },
  { value: "AiCoustics", label: "AiCoustics" },
];

export function getTranscriptionProvider(modelName) {
  return TRANSCRIPTION_PROVIDERS.find((p) => p.model_name === modelName) || null;
}

export function getDefaultTranscriptionLanguage(modelName, fallback = "auto") {
  const provider = getTranscriptionProvider(modelName);
  const languages = provider?.languages || [];
  if (languages.includes("auto")) return "auto";
  if (languages.includes("auto_detect")) return "auto_detect";
  if (languages.includes(fallback)) return fallback;
  if (languages.includes("en")) return "en";
  return languages[0] || fallback;
}

export function getNoiseSuppressionConfigDefaults(providerValue) {
  return (
    NOISE_SUPPRESSION_PROVIDERS.find((p) => p.value === providerValue)
      ?.configDefaults || undefined
  );
}
