locals {
  name_prefix = var.deployment_name
  common_tags = merge({
    Name       = var.deployment_name
    Deployment = var.deployment_name
    ManagedBy  = "terraform"
    Component  = "telnyx-contact-center"
  }, var.tags)
}

# Password is generated by Terraform but NEVER surfaced as a plain output —
# it only ever lands in the Secrets Manager secret below. The wizard reads it
# back via `aws secretsmanager get-secret-value` at runtime, not via
# `terraform output`, so it never appears in `.cc-state.json` or shell history.
resource "random_password" "db" {
  length  = 28
  special = true
  # Characters disallowed in RDS Postgres master passwords: / @ " and space.
  override_special = "!#$%^&*()-_=+[]{}<>:?"
}

resource "aws_db_subnet_group" "main" {
  name       = "${local.name_prefix}-db-subnets"
  subnet_ids = var.private_subnet_ids
  tags       = merge(local.common_tags, { Name = "${local.name_prefix}-db-subnets" })
}

resource "aws_db_parameter_group" "pg17" {
  name        = "${local.name_prefix}-pg17"
  family      = "postgres17"
  description = "Telnyx Contact Center Postgres 17 params"

  # max_connections is a STATIC parameter -> requires apply_method
  # pending-reboot. Bumped above the RDS default so multi-node HA (each node
  # holds its own pool + LISTEN/NOTIFY connections) doesn't starve.
  parameter {
    name         = "max_connections"
    value        = "300"
    apply_method = "pending-reboot"
  }
}

resource "aws_db_instance" "main" {
  identifier     = "${local.name_prefix}-pg"
  engine         = "postgres"
  engine_version = var.db_engine_version
  instance_class = var.db_instance_class

  allocated_storage     = var.db_allocated_storage
  max_allocated_storage = var.db_allocated_storage * 2
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result
  port     = 5432

  multi_az               = var.db_multi_az
  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [var.rds_security_group_id]
  parameter_group_name   = aws_db_parameter_group.pg17.name
  # Not publicly accessible: RDS lives in a private subnet reachable only
  # from app nodes via the security group (unlike the internal cc-ha-infra
  # lab, which exposes RDS publicly for admin convenience on a trusted
  # account — that's not appropriate for an external user's own AWS account).
  publicly_accessible = false

  backup_retention_period  = var.backup_retention_days
  skip_final_snapshot      = var.skip_final_snapshot
  # Static identifier (no timestamp()) so `terraform plan` doesn't show a
  # perpetual diff. If you destroy+recreate a deployment with the same name
  # more than once, delete the previous final snapshot manually first
  # (`aws rds delete-db-snapshot --db-snapshot-identifier <name>-pg-final`).
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${local.name_prefix}-pg-final"
  deletion_protection      = false
  apply_immediately        = true

  performance_insights_enabled = true
  auto_minor_version_upgrade   = true

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-pg" })
}

# Secrets Manager: full connection string + individual fields. This secret is
# Terraform-owned end to end (password generated here, value written here) —
# unlike the app/env secret (cc-secrets module), which Terraform creates as an
# empty container that the wizard populates after Telnyx bootstrap.
resource "aws_secretsmanager_secret" "db" {
  name        = "${local.name_prefix}/db/credentials"
  description = "Telnyx Contact Center RDS Postgres credentials"
  tags        = local.common_tags
  # Force immediate deletion on `terraform destroy` instead of AWS's default
  # 30-day recovery window. Without this, a destroy+re-apply of the same
  # deployment_name (e.g. `cc destroy` then `cc up` again, or this module's
  # own test/re-test cycle) fails on secretsmanager:CreateSecret with
  # ResourceExistsException("...scheduled for deletion") until the window
  # lapses or the secret is manually force-deleted.
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db.result
    engine   = "postgres"
    host     = aws_db_instance.main.address
    port     = 5432
    dbname   = var.db_name
  })
}
