"use client";
import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { FormRenderer } from "@/components/forms/FormRenderer";

export function AgentFormsView({ selectedInteraction, onBackToInteraction, formIds = [], autoOpenOnly = false }) {
  const [forms, setForms] = useState([]); const [selectedId, setSelectedId] = useState(""); const [renderData, setRenderData] = useState(null); const [message, setMessage] = useState(""); const [submitting, setSubmitting] = useState(false);
  const queueName = selectedInteraction?.queue_name || selectedInteraction?.routing_metadata?.queueName || ""; const queueId = selectedInteraction?.queue_id || selectedInteraction?.routing_metadata?.queueId || "";
  useEffect(() => { async function load() { const params = new URLSearchParams(); if (queueName) params.set("queueName", queueName); if (queueId) params.set("queueId", queueId); if (formIds.length) params.set("formIds", formIds.join(",")); const res = await fetch(`/api/contact-center/forms?${params.toString()}`, { cache: "no-store" }); const data = await res.json(); let list = data.forms || []; if (autoOpenOnly) list = list.filter((f) => f.auto_open || formIds.includes(f.id)); setForms(list); setSelectedId((prev) => prev || list[0]?.id || ""); } load(); }, [queueName, queueId, formIds.join(","), autoOpenOnly]);
  useEffect(() => { async function render() { if (!selectedId) { setRenderData(null); return; } const params = new URLSearchParams(); if (selectedInteraction?.id) params.set("interactionId", selectedInteraction.id); const res = await fetch(`/api/contact-center/forms/${selectedId}/render?${params.toString()}`, { cache: "no-store" }); const data = await res.json(); setRenderData(data.ok ? data : null); } render(); }, [selectedId, selectedInteraction?.id]);
  const selectedForm = useMemo(() => forms.find((f) => f.id === selectedId), [forms, selectedId]);
  async function submit(values) { if (!selectedId) return; setSubmitting(true); setMessage(""); const res = await fetch(`/api/contact-center/forms/${selectedId}/submissions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ interactionId: selectedInteraction?.id, data: values, context: renderData?.context }) }); const data = await res.json(); setMessage(data.ok ? "Form submitted." : (data.validation?.errors?.[0]?.message || data.error || "Submission failed")); setSubmitting(false); }
  return <div className="flex flex-col h-full overflow-hidden"><div className="px-4 py-3 bg-muted/50 border-b rounded-t-lg flex items-center justify-between"><div><h3 className="text-sm font-semibold">Forms</h3><p className="text-xs text-muted-foreground">{queueName ? `Queue: ${queueName}` : "Published agent forms"}</p></div>{onBackToInteraction ? <Button size="sm" variant="ghost" onClick={onBackToInteraction}>Back</Button> : null}</div><div className="flex-1 overflow-y-auto p-3 space-y-3">{forms.length === 0 ? <p className="text-sm text-muted-foreground">No published forms assigned to this queue.</p> : <div className="grid gap-2">{forms.map((form) => <Card key={form.id} className={`cursor-pointer ${selectedId === form.id ? "border-primary bg-primary/5" : ""}`} onClick={() => setSelectedId(form.id)}><CardContent className="p-3"><div className="flex items-center justify-between"><span className="font-medium text-sm">{form.name}</span>{form.auto_open ? <Badge variant="secondary">auto</Badge> : null}</div><p className="text-xs text-muted-foreground">{form.description || form.category}</p></CardContent></Card>)}</div>}{selectedForm && renderData ? <Card><CardContent className="p-4"><FormRenderer form={renderData.form} initialValues={renderData.initialValues} context={renderData.context} onSubmit={submit} submitting={submitting} />{message ? <p className="mt-3 text-sm text-muted-foreground">{message}</p> : null}</CardContent></Card> : null}</div></div>;
}
