"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { IconPhone, IconRefresh } from "@tabler/icons-react";
import { notify } from "@/components/ToastNotify";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";

export default function CallingSettingsPanel({ values, setValues }) {
  const [numbers, setNumbers] = useState([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState("");
  const telephony = values.telephony || {};
  const enabled = (values.enabled_features || []).includes("telephony");
  const appId = telephony.default_texml_app_id || "";
  const voicemail = telephony.voicemail_detection || {};
  const recording = telephony.recording_settings || {};

  function patch(patchValue) { setValues((current) => ({ ...current, telephony: { ...(current.telephony || {}), ...patchValue } })); }
  function toggleFeature(checked) { setValues((current) => ({ ...current, enabled_features: checked ? [...new Set([...(current.enabled_features || []), "telephony"])] : (current.enabled_features || []).filter((item) => item !== "telephony") })); }
  const loadNumbers = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/admin/numbers?page=1&pageSize=100${search ? `&phone_number=${encodeURIComponent(search)}` : ""}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Failed to load numbers"); setNumbers(Array.isArray(data.data) ? data.data : []); } catch (error) { notify({ title: "Could not load numbers", description: error.message, variant: "error" }); } finally { setLoading(false); } }, [search]);
  useEffect(() => { if (enabled) loadNumbers(); }, [enabled, loadNumbers]);
  const assigned = useMemo(() => numbers.filter((number) => String(number.connection_id || number.voice?.connection_id || "") === String(appId)), [appId, numbers]);
  async function assign(number, connectionId) { try { const response = await fetch(`/api/admin/numbers/${encodeURIComponent(number.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connection_id: connectionId || null }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Assignment failed"); notify({ title: connectionId ? "Number assigned" : "Number unassigned", description: number.phone_number, variant: "success" }); await loadNumbers(); } catch (error) { notify({ title: "Number update failed", description: error.message, variant: "error" }); } }

  return <div className="space-y-4"><Card><CardHeader><CardTitle>Voice calling</CardTitle><CardDescription>Enable telephony and configure the TeXML application that routes calls to this assistant.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex items-center justify-between rounded-lg border p-4"><div><div className="font-medium">Enable voice</div><div className="text-xs text-muted-foreground">Allow this assistant to make and receive telephone calls.</div></div><Switch checked={enabled} onCheckedChange={toggleFeature} /></div>{enabled ? <><div className="space-y-2"><Label>Default TeXML application ID *</Label><Input value={appId} onChange={(event) => patch({ default_texml_app_id: event.target.value })} placeholder="TeXML application ID" /></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Max call duration (seconds)</Label><Input type="number" min="0" value={telephony.max_call_duration_secs ?? ""} onChange={(event) => patch({ max_call_duration_secs: event.target.value ? Number(event.target.value) : undefined })} placeholder="Unlimited" /></div><div className="space-y-2"><Label>User idle timeout (seconds)</Label><Input type="number" min="0" value={telephony.user_idle_timeout_secs ?? ""} onChange={(event) => patch({ user_idle_timeout_secs: event.target.value ? Number(event.target.value) : undefined })} placeholder="Disabled" /></div></div></> : null}</CardContent></Card>
    {enabled ? <><Card><CardHeader><CardTitle>Voicemail and recording</CardTitle><CardDescription>Choose what happens when voicemail is detected and whether calls are recorded.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex items-center justify-between rounded-lg border p-4"><div><div className="font-medium">Voicemail detection</div><div className="text-xs text-muted-foreground">Detect answering machines and apply an assistant action.</div></div><Switch checked={Boolean(voicemail.on_voicemail_detected)} onCheckedChange={(checked) => patch({ voicemail_detection: checked ? { enabled: true, on_voicemail_detected: "stop" } : null })} /></div>{voicemail.on_voicemail_detected ? <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>When voicemail is detected</Label><Select value={typeof voicemail.on_voicemail_detected === "string" ? voicemail.on_voicemail_detected : "stop"} onValueChange={(value) => patch({ voicemail_detection: { ...voicemail, enabled: true, on_voicemail_detected: value } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="stop">Stop assistant</SelectItem><SelectItem value="leave_message">Leave message and stop</SelectItem><SelectItem value="continue">Continue assistant</SelectItem></SelectContent></Select></div>{voicemail.on_voicemail_detected === "leave_message" ? <div className="space-y-2"><Label>Voicemail message</Label><Textarea value={voicemail.voicemail_message || ""} onChange={(event) => patch({ voicemail_detection: { ...voicemail, voicemail_message: event.target.value } })} /></div> : null}</div> : null}<div className="flex items-center justify-between rounded-lg border p-4"><div><div className="font-medium">Call recording</div><div className="text-xs text-muted-foreground">Record calls handled by this assistant.</div></div><Switch checked={Boolean(recording.format)} onCheckedChange={(checked) => patch({ recording_settings: checked ? { format: "mp3", channels: "single" } : null })} /></div>{recording.format ? <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Format</Label><Select value={recording.format || "mp3"} onValueChange={(value) => patch({ recording_settings: { ...recording, format: value } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="mp3">MP3</SelectItem><SelectItem value="wav">WAV</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Channels</Label><Select value={recording.channels || "single"} onValueChange={(value) => patch({ recording_settings: { ...recording, channels: value } })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="single">Single</SelectItem><SelectItem value="dual">Dual</SelectItem></SelectContent></Select></div></div> : null}</CardContent></Card>
    <Card><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle>Voice numbers</CardTitle><CardDescription className="mt-1">Assign Telnyx numbers to the assistant’s TeXML application.</CardDescription></div><Badge variant="secondary">{assigned.length} assigned</Badge></div></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search phone number" /><Button variant="outline" onClick={loadNumbers} disabled={loading}><IconRefresh className="size-4" />Refresh</Button></div><div className="overflow-x-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Number</TableHead><TableHead>Type</TableHead><TableHead>Current connection</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{numbers.map((number) => { const isAssigned = String(number.connection_id || number.voice?.connection_id || "") === String(appId) && Boolean(appId); return <TableRow key={number.id}><TableCell className="font-medium"><div className="flex items-center gap-2"><IconPhone className="size-4 text-emerald-500" />{number.phone_number}</div></TableCell><TableCell>{number.number_type || "—"}</TableCell><TableCell className="max-w-64 truncate">{number.connection_name || number.connection_id || "Unassigned"}</TableCell><TableCell className="text-right"><Button size="sm" variant={isAssigned ? "outline" : "default"} disabled={!appId} onClick={() => assign(number, isAssigned ? null : appId)}>{isAssigned ? "Unassign" : "Assign"}</Button></TableCell></TableRow>; })}{!numbers.length ? <TableRow><TableCell colSpan={4} className="h-24 text-center text-muted-foreground">{loading ? "Loading…" : "No numbers found"}</TableCell></TableRow> : null}</TableBody></Table></div></CardContent></Card></> : null}
  </div>;
}
